[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 2 }
decorations = "none"

[mouse]
hide_when_typing = true

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0

[general]
import = ["~/.config/alacritty/themes/tokyonight.toml"]
