- 1.1.18
- _NAME: 'MX Ergo Multi-Device Trackball '
  _modelId: B01D406F0000
  _sensitive: {pointer_speed: true, speed-change: false}
  _serial: 058C13FC
  _speed-change: 205
  _unitId: 4F1BB6D2
  _wpid: 406F
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 91: 0, 93: 0, 237: 1}
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  pointer_speed: 269
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93, 237: 237}
  speed-change: 237
- _NAME: M240 Silent
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, scroll-ratchet-torque, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, persistent-remappable-keys, disable-keyboard-keys, force-sensing, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform,
    change-host, gesture2-gestures, gesture2-divert, gesture2-params, haptic-level, haptic-play, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03A00000000
  _sensitive: {dpi: false, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, lowres-scroll-mode: false}
  _unitId: DC760395
  divert-keys: {82: 0}
  dpi: 1100
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82}
- _NAME: Pebble Keys 2 K380s
  _modelId: B37700000000
  _sensitive: {fn-swap: false, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: BED775DF
  change-host: null
  disable-keyboard-keys: {1: false, 8: false, 16: false}
  divert-keys: {110: 0, 206: 0, 212: 0, 229: 0, 231: 0, 232: 0, 233: 0, 259: 0, 264: 0, 266: 0, 279: 0}
  fn-swap: false
  multiplatform: 0
